name: validate

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize] # This will trigger the workflow only when a PR is opened or updated with new commits
  workflow_dispatch:

jobs:
  ig-publisher-r4:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Preprocess and validate R4 IG
        run: |
          chmod u+x *.sh
          ./_preProcessAndCheckAll.sh 4.0.1


  ig-publisher-r5:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Preprocess and validate R5 IG
        run: |
          chmod u+x *.sh
          ./_preProcessAndCheckAll.sh 5.0.0

